name: Docker Build  - Development

on:
  push:
    branches:
      - DockerFile2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Docker Image with docker-compose
        env:
          NODE_ENV: production
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          MY_SECRET: ${{ secrets.MY_SECRET }}
          SENDINBLUESMTP: ${{ secrets.SENDINBLUESMTP }}
          SENDINBLUEAPI: ${{ secrets.SENDINBLUEAPI }}
          RECAPTCHA_SITE: ${{ secrets.RECAPTCHA_PROD_SITE }}
          RECAPTCHA_SECRET: ${{ secrets.RECAPTCHA_PROD_SECRET }}
          MONGOURI_PROD: ${{ secrets.MONGOURI_PROD }}
          PORT: ${{ secrets.PORT }}
          DOCKER_IMAGENAME: ${{ secrets.DOCKER_IMAGENAME }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker compose -f docker-compose.yml build
        # Replace `/path/to/your/docker-compose.yml` with the actual path to your docker-compose.yml file.

      # - name: Build Docker Image
      #   run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mathgenius:1 .
      # Replace `your-docker-username` and `your-image-name` with your Docker Hub username and image name.

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mathgeniusimage:dev
